apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flink

resources:
  #- https://raw.githubusercontent.com/apache/flink-kubernetes-operator/release-1.9/examples/basic.yaml
  - basic-flink-application-deployment.yaml